(() => {
  'use strict';

  const cfg=window.IJR_COLAB_ACTIVITY_CONFIG;
  const $=id=>document.getElementById(id);
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const PYODIDE_INDEX='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/';
  const PLACEHOLDER='WRITE_HERE';
  const TOTAL_MINUTES=Number(cfg.targetMinutes||40);

  const state={
    attemptId:null,token:null,snapshot:null,currentCp:null,pendingNextSnapshot:null,
    restrictionEvents:0,pyodide:null,runtimePromise:null,pandasReady:false,datasetReady:false,
    executionCount:0,currentKey:null,currentStarter:'',lastCellOutput:'',lastCellScalar:'',
    startedAt:null,timerHandle:null
  };

  const LESSONS={
    A1:{minutes:4,tag:'FOUNDATION · VARIABLES',title:'Variables and addition',
      concept:'<p>A <strong>variable</strong> is a name that stores a value. In Python, <code>=</code> assigns a value and <code>+</code> adds numbers.</p><p>Your team should read, complete one small line, run it, and explain what happened. <small>Variable = nombre que guarda un valor.</small></p>',
      goal:'<p>Recognize the flow <strong>value → variable → operation → output</strong> and distinguish assigning a value from printing it.</p>',
      steps:['Identify the value stored in <code>a</code> and in <code>b</code>.','Replace <code>WRITE_HERE</code> with an expression that adds <code>a</code> and <code>b</code>.','Do not type the numeric answer manually; make Python calculate it.','Run the cell, read the output, and validate only when your team can explain which line produced it.'],
      task:'<p>Create <code>result</code> from the sum of <code>a</code> and <code>b</code>, then display it with <code>print()</code>.</p>',
      explore:'<p>Try <code>type(a)</code> and <code>a == 12</code> in the console.</p>',
      hints:['Think about the arithmetic operator Python uses for addition.','Use the <strong>variable names</strong> <code>a</code> and <code>b</code>, not the numbers written again.','The structure you need is <code>result = a + b</code>.'],
      starter:`a = 12\nb = 5\n\n# TODO: build the sum using variables a and b\nresult = WRITE_HERE\n\nprint(result)`,
      solution:`a = 12\nb = 5\n\nresult = a + b\n\nprint(result)`},
    A2:{minutes:3,tag:'FOUNDATION · OPERATORS',title:'Multiplication as an operation',
      concept:'<p>Arithmetic operators transform data. Python represents multiplication with <code>*</code>. The result of an expression can be stored and reused. <small>Multiplicación en Python: <code>*</code>.</small></p>',
      goal:'<p>Distinguish <strong>input data</strong>, the <strong>operation</strong>, and the <strong>result</strong>.</p>',
      steps:['Identify the input variables <code>a</code> and <code>b</code>.','Complete only <code>WRITE_HERE</code>; this time you need multiplication.','Run the code. If Python reports an error, read the message before editing.','Before validating, try <code>a ** 2</code> in the console and compare the operators.'],
      task:'<p>Create <code>product</code> from the two existing variables and produce one numeric output.</p>',
      explore:'<p>Try <code>a ** 2</code>. The operators <code>*</code> and <code>**</code> do different things.</p>',
      hints:['The mathematical × symbol is not typed the same way in Python.','Use an asterisk <code>*</code> between the two variable names.','The complete line is <code>product = a * b</code>.'],
      starter:`a = 12\nb = 5\n\n# TODO: build the product using a and b\nproduct = WRITE_HERE\n\nprint(product)`,
      solution:`a = 12\nb = 5\n\nproduct = a * b\n\nprint(product)`},
    A3:{minutes:4,tag:'DATA STRUCTURES · LISTS',title:'A list stores many values',
      concept:'<p>A Python <strong>list</strong> stores several observations in one object using brackets <code>[ ]</code>. Before summarizing data, we often need to know how many observations we have. <small>Lista = colección de valores.</small></p>',
      goal:'<p>Move from single values to a collection and obtain its size with a function.</p>',
      steps:['Look at <code>numbers</code>; do not count the values manually.','Find the Python function that returns the number of elements.','Complete <code>count = WRITE_HERE</code>.','Run the cell, then explore <code>numbers[0]</code> and <code>numbers[-1]</code>.'],
      task:'<p>Make Python determine how many observations are stored in <code>numbers</code>.</p>',
      explore:'<p>Try <code>type(numbers)</code>, <code>numbers[0]</code>, and <code>numbers[-1]</code>.</p>',
      hints:['You need a function that measures the length of a collection.','The function is <code>len(...)</code>; place the list name inside the parentheses.','The complete line is <code>count = len(numbers)</code>.'],
      starter:`numbers = [12, 7, 15, 9, 11]\n\n# TODO: calculate how many elements numbers contains\ncount = WRITE_HERE\n\nprint(count)`,
      solution:`numbers = [12, 7, 15, 9, 11]\n\ncount = len(numbers)\n\nprint(count)`},
    A4:{minutes:4,tag:'DATA OPERATIONS · AGGREGATION',title:'Aggregate a list with sum()',
      concept:'<p>An <strong>aggregation</strong> turns many observations into one summary value. Adding all values is a first example of aggregation. <small>Agregación = resumir varios datos en un valor.</small></p>',
      goal:'<p>Use a function that receives a complete collection and returns one number.</p>',
      steps:['Think about what the total of the list means.','Do not add each value manually in the code.','Complete <code>total</code> with a function that works on the whole list.','Then try <code>min(numbers)</code> and <code>max(numbers)</code>.'],
      task:'<p>Calculate the total of all observations with a Python function.</p>',
      explore:'<p>Compare <code>sum()</code>, <code>min()</code>, and <code>max()</code>.</p>',
      hints:['Look for a function whose name means “suma”.','The function is <code>sum(...)</code>.','The complete line is <code>total = sum(numbers)</code>.'],
      starter:`numbers = [12, 7, 15, 9, 11]\n\n# TODO: obtain the total of the list with a Python function\ntotal = WRITE_HERE\n\nprint(total)`,
      solution:`numbers = [12, 7, 15, 9, 11]\n\ntotal = sum(numbers)\n\nprint(total)`},
    A5:{minutes:5,tag:'STATISTICS · MEAN',title:'Build the arithmetic mean',
      concept:'<p>The arithmetic mean combines two ideas you already used: <strong>add</strong> the observations and <strong>count</strong> them.</p><p>In statistics: <strong>x̄ = Σxᵢ / n</strong>. Your Python expression should represent the same structure. <small>Media = suma de datos ÷ cantidad de datos.</small></p>',
      goal:'<p>Translate a statistical formula into an executable Python expression.</p>',
      steps:['Identify the numerator and denominator in the formula.','Connect the numerator to a function you already used.','Connect the denominator to the function that counts elements.','Complete <code>mean_value</code>, run it, and explain why the result is a decimal.'],
      task:'<p>Build the mean of <code>numbers</code> using operations on the list.</p>',
      explore:'<p>Try <code>round(mean_value, 1)</code> and compare the two values.</p>',
      hints:['The statistical recipe is “total divided by count”.','Combine <code>sum(numbers)</code> and <code>len(numbers)</code> with the division operator <code>/</code>.','The complete line is <code>mean_value = sum(numbers) / len(numbers)</code>.'],
      starter:`numbers = [12, 7, 15, 9, 11]\n\n# TODO: translate the mean formula into Python\nmean_value = WRITE_HERE\n\nprint(mean_value)`,
      solution:`numbers = [12, 7, 15, 9, 11]\n\nmean_value = sum(numbers) / len(numbers)\n\nprint(mean_value)`},
    A6:{minutes:7,tag:'PANDAS · EXTERNAL DATA',title:'Load a real CSV file',
      concept:'<p>Now the data are no longer written directly inside the program. A <strong>CSV</strong> stores rows and columns, and <code>pandas</code> converts it into a <strong>DataFrame</strong>.</p><p>The class file is available in this workspace as <code>data.csv</code>. <small>CSV = archivo de datos en filas y columnas.</small></p>',
      goal:'<p>Take the first step from basic Python to real tabular data analysis.</p>',
      steps:['Identify what <code>import pandas</code> and <code>pd.read_csv()</code> do.','Inspect <code>df.head(3)</code> to identify the columns.','You only need the number of rows; investigate <code>df.shape</code>.','Complete <code>row_count</code> and leave only the row count as the final printed output.'],
      task:'<p>Load <code>data.csv</code>, inspect its first rows, and produce the number of records.</p>',
      explore:'<p>Try <code>df.columns</code>, <code>df.shape</code>, and <code>df.dtypes</code>.</p>',
      hints:['<code>df.shape</code> returns two numbers: rows and columns.','The first item of a pair is selected with index <code>[0]</code>.','The complete line is <code>row_count = df.shape[0]</code>.'],
      starter:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\nprint(df.head(3))\n\n# TODO: obtain only the number of rows in the DataFrame\nrow_count = WRITE_HERE\n\nprint(row_count)`,
      solution:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\nprint(df.head(3))\n\nrow_count = df.shape[0]\n\nprint(row_count)`},
    A7:{minutes:5,tag:'PANDAS · COLUMN ANALYSIS',title:'Calculate a column mean',
      concept:'<p>A DataFrame organizes variables by columns. Selecting <code>df["score"]</code> creates a Series on which statistical methods can be applied. <small>Columna = una variable del conjunto de datos.</small></p>',
      goal:'<p>Perform a statistical operation directly on one DataFrame column.</p>',
      steps:['Load the file and identify the <code>score</code> column.','Select that column with brackets.','Find the Pandas method that calculates a mean.','Run it and then try <code>df["score"].describe()</code>.'],
      task:'<p>Use Pandas to calculate the mean of the <code>score</code> column.</p>',
      explore:'<p>With <code>describe()</code>, identify <em>count</em>, <em>mean</em>, <em>min</em>, and <em>max</em>.</p>',
      hints:['First select one DataFrame column.','After <code>df["score"]</code>, call the <code>.mean()</code> method.','The complete line is <code>score_mean = df["score"].mean()</code>.'],
      starter:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\n\n# TODO: calculate the mean of the score column\nscore_mean = WRITE_HERE\n\nprint(score_mean)`,
      solution:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\n\nscore_mean = df["score"].mean()\n\nprint(score_mean)`},
    A8:{minutes:5,tag:'PANDAS · FILTERING',title:'Filter rows with a condition',
      concept:'<p>Data analysis also means <strong>selecting</strong> records. A comparison on a column produces <code>True</code>/<code>False</code> values, and that condition can be used as a filter. <small>Filtrar = seleccionar filas que cumplen una condición.</small></p>',
      goal:'<p>Build a basic query using <strong>select → filter → count</strong>.</p>',
      steps:['Write the condition “score greater than or equal to 4”.','Use that condition inside brackets to create <code>passed</code>.','Count how many rows remain in <code>passed</code>.','Run it, then inspect <code>passed[["student_id", "score"]]</code>.'],
      task:'<p>Filter records with <code>score</code> greater than or equal to 4 and count how many satisfy the condition.</p>',
      explore:'<p>Temporarily change the threshold in the console and observe how the subset changes.</p>',
      hints:['A Pandas filter usually has the form <code>df[condition]</code>.','The condition is <code>df["score"] &gt;= 4</code>; then you can reuse <code>len()</code>.','Use <code>passed = df[df["score"] &gt;= 4]</code> and <code>passed_count = len(passed)</code>.'],
      starter:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\n\n# TODO 1: create a DataFrame with score greater than or equal to 4\npassed = WRITE_HERE\n\n# TODO 2: count how many rows remain after filtering\npassed_count = WRITE_HERE\n\nprint(passed_count)`,
      solution:`import pandas as pd\n\ndf = pd.read_csv("data.csv")\n\npassed = df[df["score"] >= 4]\npassed_count = len(passed)\n\nprint(passed_count)`}
  };

  async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message||'Backend error');return data;}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function fmtGrade(v){return Number(v??1).toFixed(2)}
  function normalizeCode(v){return String(v??'').replace(/\\n/g,'\n')}
  function save(){if(state.attemptId&&state.token)sessionStorage.setItem(cfg.sessionStorageKey,JSON.stringify({attemptId:state.attemptId,token:state.token}));}
  function clearSaved(){sessionStorage.removeItem(cfg.sessionStorageKey)}
  function activityActive(){return !!state.snapshot&&!state.snapshot.completed}
  function fullscreenSupported(){return !!document.documentElement.requestFullscreen}
  function isFullscreen(){return !!document.fullscreenElement}
  function setSetupStatus(msg,bad=false){const el=$('setupStatus');el.textContent=msg||'';el.style.color=bad?'#b3261e':''}
  function setValidation(msg,kind=''){const el=$('activityStatus');el.textContent=msg||'';el.className=`validation-status ${kind}`.trim()}

  function setRuntimeBadge(mode,label){const badge=$('runtimeBadge');badge.className=`runtime-badge ${mode}`;badge.innerHTML='<span class="status-dot"></span>'+esc(label);const kernel=$('kernelLabel');const info=document.querySelector('.kernel-info');if(kernel){kernel.textContent=mode==='ready'?'Python 3 · connected in browser':label;info?.classList.toggle('ready',mode==='ready')}}
  function updateRestrictionLabel(){const el=$('restrictionLabel');if(!el)return;el.textContent=state.restrictionEvents>0?`Exits: ${state.restrictionEvents}`:'Guided mode';el.classList.toggle('attention',state.restrictionEvents>0)}
  async function logEvent(type,metadata={}){if(!state.attemptId||!state.token||!cfg.rpc.event)return null;try{const data=await rpc(cfg.rpc.event,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_event_type:type,p_metadata:metadata});if(Number.isFinite(Number(data?.restriction_events))){state.restrictionEvents=Number(data.restriction_events);updateRestrictionLabel()}return data}catch(err){console.warn('activity event log failed',type,err);return null}}
  function hideFullscreenGate(){$('fullscreenGate')?.classList.add('hidden')}
  function showFullscreenGate(message){if(!cfg.requireFullscreen){hideFullscreenGate();return}$('fullscreenMessage').textContent=message||'The lab is waiting for fullscreen mode.';$('fullscreenGate').classList.remove('hidden')}
  async function enterFullscreen(){if(!cfg.requireFullscreen){hideFullscreenGate();return true}if(!fullscreenSupported()){showFullscreenGate('This browser does not support the required fullscreen mode. Use Chrome or Edge on a computer.');return false}if(isFullscreen()){hideFullscreenGate();return true}try{await document.documentElement.requestFullscreen();hideFullscreenGate();await logEvent('FULLSCREEN_ENTER',{source:'student_action'});return true}catch(_){showFullscreenGate('Allow fullscreen mode to continue working in the lab.');return false}}
  function enforceFullscreen(){if(!cfg.requireFullscreen||!activityActive()){hideFullscreenGate();return true}if(isFullscreen()){hideFullscreenGate();return true}showFullscreenGate('Lab paused. Return to fullscreen mode to continue.');return false}

  function clearTerminal(message='Python console ready.'){const out=$('terminalOutput');out.textContent=message+'\n';out.scrollTop=out.scrollHeight}
  function appendTerminal(text){const out=$('terminalOutput');const prefix=out.textContent&&!out.textContent.endsWith('\n')?'\n':'';out.textContent+=prefix+String(text??'')+(String(text??'').endsWith('\n')?'':'\n');out.scrollTop=out.scrollHeight}
  function lastScalar(output){const lines=String(output||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return lines.length?lines[lines.length-1]:''}

  async function ensureRuntime(){if(state.pyodide)return state.pyodide;if(state.runtimePromise)return state.runtimePromise;state.runtimePromise=(async()=>{try{setRuntimeBadge('loading','Loading Python…');if(typeof window.loadPyodide!=='function')throw new Error('Pyodide did not load. Check the network connection.');const py=await window.loadPyodide({indexURL:PYODIDE_INDEX});py.setStdin({stdin:()=>window.prompt('Python input:')??null});try{py.FS.mkdirTree('/home/pyodide')}catch(_){}await py.runPythonAsync("import os\nos.chdir('/home/pyodide')");try{const response=await fetch('data.csv',{cache:'no-store'});if(!response.ok)throw new Error(`CSV HTTP ${response.status}`);py.FS.writeFile('/home/pyodide/data.csv',await response.text());state.datasetReady=true}catch(err){state.datasetReady=false;console.warn('dataset preload failed',err)}state.pyodide=py;setRuntimeBadge('ready','Python ready');clearTerminal('Python 3 runtime ready.\nWorkspace ready for your team.');return py}catch(err){state.runtimePromise=null;setRuntimeBadge('error','Python unavailable');clearTerminal(`Runtime error: ${err.message}`);setValidation('Python could not start. Check the connection and reload the page.','bad');throw err}})();return state.runtimePromise}
  async function ensurePandas(){const py=await ensureRuntime();if(state.pandasReady)return;setRuntimeBadge('loading','Loading Pandas…');appendTerminal('[system] Loading pandas…');await py.loadPackage('pandas');state.pandasReady=true;setRuntimeBadge('ready','Python + Pandas ready');appendTerminal('[system] pandas ready.')}
  async function executePython(source,{cell=false,terminal=false}={}){if(!enforceFullscreen())return null;const py=await ensureRuntime();if(/(^|\n)\s*(import pandas|from pandas)/.test(source))await ensurePandas();const stdout=[],stderr=[];py.setStdout({batched:msg=>stdout.push(msg)});py.setStderr({batched:msg=>stderr.push(msg)});let result;try{result=await py.runPythonAsync(source);if(result!==undefined&&result!==null){const text=String(result);if(text!=='None')stdout.push(text);if(typeof result.destroy==='function')result.destroy()}}catch(err){stderr.push(String(err?.message||err))}const output=stdout.join('\n').trim(),errors=stderr.join('\n').trim();if(cell){state.executionCount+=1;$('executionCount').textContent=`[${state.executionCount}]`;appendTerminal(`\nIn [${state.executionCount}]:`);if(output)appendTerminal(output);if(errors)appendTerminal(`ERROR\n${errors}`);state.lastCellOutput=errors?'':output;state.lastCellScalar=errors?'':lastScalar(output);$('validateButton').disabled=!state.lastCellScalar;if(errors)setValidation('Python found an error. Read it, fix the code, and run again. This execution error does not cost points.','bad');else if(state.lastCellScalar)setValidation('The cell produced an output. If your team can explain it, press Validate output.');else if(output)setValidation('The last output is not yet a value that can be validated. Check the guide.','bad');else setValidation('The cell did not print an output. Check whether print(...) is missing.','bad')}else if(terminal){if(output)appendTerminal(output);if(errors)appendTerminal(`ERROR\n${errors}`)}return{output,errors}}

  function renderMath(){if(typeof window.renderMathInElement!=='function')return;try{window.renderMathInElement($('guidePane'),{delimiters:[{left:'\\(',right:'\\)',display:false},{left:'\\[',right:'\\]',display:true}],throwOnError:false})}catch(err){console.warn('math render skipped',err)}}
  function currentCheckpoint(snapshot=state.snapshot){return Array.from(snapshot?.checkpoints||[]).find(cp=>!cp.completed)||null}
  function formatElapsed(ms){const total=Math.max(0,Math.floor(ms/1000)),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
  function elapsedMs(){return state.startedAt?Math.max(0,Date.now()-state.startedAt.getTime()):0}
  function updateTimer(){const el=$('timeLabel');if(!el)return;const ms=elapsedMs(),target=TOTAL_MINUTES*60000;el.textContent=`${formatElapsed(ms)} / ${String(TOTAL_MINUTES).padStart(2,'0')}:00`;el.classList.toggle('warn',ms>=35*60000&&ms<target);el.classList.toggle('over',ms>=target)}
  function startTimer(startedAt){if(startedAt){const d=new Date(startedAt);if(!Number.isNaN(d.getTime()))state.startedAt=d}if(!state.startedAt)state.startedAt=new Date();clearInterval(state.timerHandle);updateTimer();state.timerHandle=setInterval(updateTimer,1000)}
  function updateHelpUI(snapshot=state.snapshot){const remaining=Number(snapshot?.help_tokens_remaining??cfg.helpTokenLimit??3),used=Number(snapshot?.help_tokens_used||0);$('helpBadge').textContent=`${remaining} help${remaining===1?'':'s'}`;$('helpBadge').classList.toggle('empty',remaining<=0);$('helpRemainingText').textContent=`${remaining} of ${cfg.helpTokenLimit||3} remaining`;$('helpButton').disabled=remaining<=0||!state.currentCp||!!state.currentCp.completed;$('helpButton').textContent=remaining>0?'Use 1 help':'No helps remaining';$('finishHelps').textContent=`${used} / ${cfg.helpTokenLimit||3}`}
  function updatePenaltyStatus(cp=state.currentCp){if(!cp){$('penaltyStatus').textContent='';return}const wrong=Number(cp.wrong_attempts||0),helps=Number(cp.help_count||0),potential=Number(cp.stage_potential??cp.points??1);$('penaltyStatus').textContent=`This stage can still earn ${potential.toFixed(2)} / ${Number(cp.points||1).toFixed(2)} points · validated errors: ${wrong} · helps used here: ${helps}.`;$('skipButton').classList.toggle('hidden',wrong<=0||cp.completed)}
  function updateSnapshotMetrics(snapshot){state.snapshot=snapshot;const checkpoints=Array.from(snapshot.checkpoints||[]),completed=Number(snapshot.completed_count??checkpoints.filter(c=>c.completed).length),total=Number(snapshot.checkpoint_count||checkpoints.length||8);$('gradeLabel').textContent=`Projected ${fmtGrade(snapshot.projected_grade??snapshot.grade)} / 5.00`;$('progressText').textContent=`${completed} / ${total} completed`;$('progressBar').style.width=`${Math.min(100,completed/Math.max(1,total)*100)}%`;updateHelpUI(snapshot);updateRestrictionLabel()}
  function renderStepRail(checkpoints,currentKey){$('stepRail').innerHTML=checkpoints.map(cp=>{let cls='';if(cp.completed){cls=cp.completion_mode==='revealed'?'revealed':cp.completion_mode==='skipped'?'skipped':'done'}else if(cp.key===currentKey)cls='active';return `<span class="step-dot ${cls}" title="Stage ${esc(cp.sequence)} · ${esc(cp.completion_mode||'pending')}"></span>`}).join('')}
  function showExistingHelp(cp,lesson){const count=Number(cp?.help_count||0),panel=$('helpPanel');if(count<=0){panel.classList.add('hidden');panel.innerHTML='';return}const index=Math.min(count,lesson.hints.length)-1;panel.innerHTML=`<strong>Help ${count} used on this stage</strong>${lesson.hints[index]}`;panel.classList.remove('hidden')}

  function renderLesson(cp){const lesson=LESSONS[cp.key]||{minutes:4,tag:'PYTHON LAB',title:cp.title,concept:`<p>${esc(cp.prompt)}</p>`,goal:'<p>Run Python and interpret its output.</p>',steps:['Read the task.','Complete the code.','Run it and inspect the output.','Validate when your team can explain the result.'],task:`<p>${esc(cp.prompt)}</p>`,explore:'<p>Use the console to inspect variables.</p>',hints:[esc(cp.hint||'Review the task.'),esc(cp.hint||'Review the task.'),esc(cp.hint||'Review the task.')],starter:normalizeCode(cp.code),solution:normalizeCode(cp.code)};state.currentCp=cp;state.currentKey=cp.key;state.currentStarter=lesson.starter||normalizeCode(cp.code);state.lastCellOutput='';state.lastCellScalar='';state.executionCount=0;state.pendingNextSnapshot=null;$('lessonTag').textContent=lesson.tag;$('lessonTiming').textContent=`Target: ${lesson.minutes} min`;$('lessonTitle').textContent=lesson.title;$('lessonConcept').innerHTML=lesson.concept;$('lessonGoal').innerHTML=lesson.goal;$('lessonSteps').innerHTML=(lesson.steps||[]).map((step,index)=>`<li><span>${index+1}</span><div>${step}</div></li>`).join('');$('lessonTask').innerHTML=lesson.task;$('lessonExplore').innerHTML=lesson.explore;$('codeEditor').value=state.currentStarter;$('validateButton').disabled=true;$('executionCount').textContent='[ ]';$('solutionPanel').classList.add('hidden');$('revealButton').disabled=false;$('runCodeButton').disabled=false;$('runCellButton').disabled=false;$('resetCodeButton').disabled=false;showExistingHelp(cp,lesson);updateHelpUI();updatePenaltyStatus(cp);setValidation('Read the guide, complete WRITE_HERE, and run the cell. You can fix code without a penalty.');renderMath()}

  function render(snapshot){updateSnapshotMetrics(snapshot);$('setupPanel').classList.add('hidden');const checkpoints=Array.from(snapshot.checkpoints||[]),completed=Number(snapshot.completed_count??checkpoints.filter(c=>c.completed).length),total=Number(snapshot.checkpoint_count||checkpoints.length||8);$('studentLabel').textContent=`${snapshot.group_code} · ${snapshot.student_label}`;startTimer(snapshot.started_at);if(snapshot.completed){clearInterval(state.timerHandle);$('workspacePanel').classList.add('hidden');$('finishPanel').classList.remove('hidden');$('finishPoints').textContent=`${completed} / ${total}`;$('finishGrade').textContent=fmtGrade(snapshot.grade);$('finishHelps').textContent=`${snapshot.help_tokens_used||0} / ${cfg.helpTokenLimit||3}`;$('finishTime').textContent=formatElapsed(elapsedMs());hideFullscreenGate();clearSaved();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});return}const current=currentCheckpoint(snapshot)||checkpoints[0];const n=Number(current?.sequence||completed+1);$('stepLabel').textContent=`Stage ${n} of ${total}`;renderStepRail(checkpoints,current?.key);renderLesson(current);$('finishPanel').classList.add('hidden');$('workspacePanel').classList.remove('hidden');enforceFullscreen();ensureRuntime().catch(()=>{})}

  async function runCurrentCell(){if(!enforceFullscreen())return;const source=$('codeEditor').value;if(!source.trim()){setValidation('The cell is empty. Reset it and complete the code.','bad');return}if(source.includes(PLACEHOLDER)){setValidation('There is still a WRITE_HERE marker. Replace every marker before running the cell.','bad');return}$('runCodeButton').disabled=true;$('runCellButton').disabled=true;try{await executePython(source,{cell:true})}finally{$('runCodeButton').disabled=false;$('runCellButton').disabled=false}}

  async function validateCurrent(){if(!enforceFullscreen())return;if(!state.currentKey||!state.lastCellScalar){setValidation('First run a cell that produces a validatable output.','bad');return}const btn=$('validateButton');btn.disabled=true;setValidation('Validating your team output…');try{const data=await rpc(cfg.rpc.submit,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.currentKey,p_answer:state.lastCellScalar});if(data.correct){setValidation(`Correct. This stage earned ${Number(data.awarded_points||0).toFixed(2)} / 1.00 points.`,'ok');appendTerminal(`✓ Stage validated · ${Number(data.awarded_points||0).toFixed(2)} points.`);await logEvent('LAB_STAGE_COMPLETED',{checkpoint_key:state.currentKey,execution_count:state.executionCount,awarded_points:data.awarded_points,workspace_version:'guided-v5'});setTimeout(()=>render(data.snapshot),900)}else{state.snapshot=data.snapshot;state.currentCp=(data.snapshot.checkpoints||[]).find(cp=>cp.key===state.currentKey)||state.currentCp;updateSnapshotMetrics(data.snapshot);renderStepRail(data.snapshot.checkpoints||[],state.currentKey);updatePenaltyStatus(state.currentCp);setValidation(`Incorrect output recorded. Validated error #${data.wrong_attempts}. You may retry, use a help token, reveal the solution, or continue without solving.`,'bad');appendTerminal(`✗ Incorrect validation #${data.wrong_attempts}. Projected grade updated.`);btn.disabled=false}}catch(err){setValidation(`This stage could not be recorded: ${err.message}`,'bad');btn.disabled=false}}

  async function useHelp(){if(!enforceFullscreen()||!state.currentKey)return;const remaining=Number(state.snapshot?.help_tokens_remaining??3);if(remaining<=0)return;if(!window.confirm(`Use one help token on this stage? ${remaining} remain. Each help lowers the projected maximum grade by 0.10.`))return;$('helpButton').disabled=true;try{const data=await rpc(cfg.rpc.help,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.currentKey});state.snapshot=data.snapshot;state.currentCp=(data.snapshot.checkpoints||[]).find(cp=>cp.key===state.currentKey)||state.currentCp;updateSnapshotMetrics(data.snapshot);updatePenaltyStatus(state.currentCp);const lesson=LESSONS[state.currentKey],level=Math.min(Number(data.help_level||1),lesson.hints.length);$('helpPanel').innerHTML=`<strong>Help ${level}</strong>${lesson.hints[level-1]}`;$('helpPanel').classList.remove('hidden');renderMath();setValidation(`Help ${data.help_tokens_used} of ${cfg.helpTokenLimit||3} recorded. Read the hint and return to the code.`);await logEvent('HELP_SHOWN',{checkpoint_key:state.currentKey,help_level:level,workspace_version:'guided-v5'})}catch(err){setValidation(`Help could not be used: ${err.message}`,'bad')}finally{updateHelpUI()}}

  async function revealSolution(){if(!enforceFullscreen()||!state.currentKey)return;if(!window.confirm('Revealing the complete solution closes this stage for 25% of its value. Continue?'))return;$('revealButton').disabled=true;try{const key=state.currentKey,data=await rpc(cfg.rpc.reveal,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:key});state.pendingNextSnapshot=data.snapshot;updateSnapshotMetrics(data.snapshot);const lesson=LESSONS[key];$('solutionCode').textContent=lesson.solution;$('solutionOutput').textContent=data.expected_answer;$('solutionCredit').textContent=`${Math.round(Number(data.awarded_points||0)*100)}% of stage`;$('solutionPanel').classList.remove('hidden');$('runCodeButton').disabled=true;$('runCellButton').disabled=true;$('resetCodeButton').disabled=true;$('validateButton').disabled=true;$('helpButton').disabled=true;$('skipButton').classList.add('hidden');setValidation('Solution revealed and recorded. Study each line before continuing.','ok');appendTerminal(`↳ Solution revealed · ${Number(data.awarded_points||0).toFixed(2)} points.`)}catch(err){setValidation(`The solution could not be revealed: ${err.message}`,'bad');$('revealButton').disabled=false}}

  async function skipStage(){if(!enforceFullscreen()||!state.currentKey)return;if(!window.confirm('Continuing without solving gives 0% for this stage. Continue?'))return;$('skipButton').disabled=true;try{const data=await rpc(cfg.rpc.skip,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.currentKey});appendTerminal('↳ Stage skipped · 0.00 points.');render(data.snapshot)}catch(err){setValidation(`Could not continue: ${err.message}`,'bad');$('skipButton').disabled=false}}

  function updateTeamSizeUI(){const size=Number($('teamSize').value||3),show=size===3;$('student3Wrap').classList.toggle('hidden-member',!show);$('studentName3').required=show;if(!show)$('studentName3').value=''}
  function readTeamNames(){const size=Number($('teamSize').value||3),names=[$('studentName1').value.trim(),$('studentName2').value.trim()];if(size===3)names.push($('studentName3').value.trim());return names}
  $('teamSize').addEventListener('change',updateTeamSizeUI);updateTeamSizeUI();

  $('registrationForm').addEventListener('submit',async e=>{e.preventDefault();const group=$('groupCode').value,names=readTeamNames();if(!group||names.some(n=>n.length<2)){setSetupStatus('Complete the group and the full name of each team member.',true);return}const normalized=names.map(x=>x.toLocaleLowerCase('es').replace(/\s+/g,' ').trim());if(new Set(normalized).size!==normalized.length){setSetupStatus('Do not repeat the same name within the team.',true);return}if(cfg.requireFullscreen){if(!fullscreenSupported()){setSetupStatus('This browser does not support required fullscreen mode. Use Chrome or Edge.',true);return}if(!await enterFullscreen())return}$('startButton').disabled=true;setSetupStatus('Registering your team and preparing Python…');try{const data=await rpc(cfg.rpc.startTeam,{p_activity_slug:cfg.activitySlug,p_student_names:names,p_group_code:group,p_session_id:crypto.randomUUID(),p_user_agent:navigator.userAgent});state.attemptId=data.attempt_id;state.token=data.attempt_token;save();render(data.snapshot);setSetupStatus('');await logEvent('ACTIVITY_READY',{identity_mode:'team',team_size:names.length,target_minutes:TOTAL_MINUTES,workspace_version:'guided-v5'})}catch(err){$('startButton').disabled=false;setSetupStatus(`Could not start the lab: ${err.message}`,true);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})}});

  $('runCodeButton').addEventListener('click',runCurrentCell);$('runCellButton').addEventListener('click',runCurrentCell);$('validateButton').addEventListener('click',validateCurrent);$('helpButton').addEventListener('click',useHelp);$('revealButton').addEventListener('click',revealSolution);$('skipButton').addEventListener('click',skipStage);$('continueAfterRevealButton').addEventListener('click',()=>{if(state.pendingNextSnapshot)render(state.pendingNextSnapshot)});
  $('resetCodeButton').addEventListener('click',()=>{if(!enforceFullscreen())return;$('codeEditor').value=state.currentStarter;state.lastCellOutput='';state.lastCellScalar='';state.executionCount=0;$('executionCount').textContent='[ ]';$('validateButton').disabled=true;setValidation('Cell reset. Read the steps and complete WRITE_HERE again.')});
  $('clearTerminalButton').addEventListener('click',()=>clearTerminal('Python console cleared.'));
  $('terminalForm').addEventListener('submit',async e=>{e.preventDefault();if(!enforceFullscreen())return;const input=$('terminalCommand'),command=input.value.trim();if(!command)return;input.value='';appendTerminal(`>>> ${command}`);try{await executePython(command,{terminal:true})}catch(err){appendTerminal(`ERROR\n${err.message}`)}});
  $('codeEditor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const editor=e.currentTarget,start=editor.selectionStart,end=editor.selectionEnd;editor.setRangeText('    ',start,end,'end')}if((e.shiftKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();runCurrentCell()}});
  $('enterFullscreenButton').addEventListener('click',enterFullscreen);
  document.addEventListener('fullscreenchange',async()=>{if(!activityActive()||!cfg.requireFullscreen){hideFullscreenGate();return}if(isFullscreen()){hideFullscreenGate();await logEvent('FULLSCREEN_ENTER',{source:'fullscreenchange',workspace_version:'guided-v5'})}else{showFullscreenGate('You left fullscreen mode. Return to fullscreen to continue.');await logEvent('FULLSCREEN_EXIT',{visibility:document.visibilityState,workspace_version:'guided-v5'})}});
  document.addEventListener('visibilitychange',async()=>{if(!activityActive())return;if(document.visibilityState==='hidden')await logEvent('UNAUTHORIZED_LEAVE',{reason:'visibility_hidden',workspace_version:'guided-v5'});else enforceFullscreen()});
  window.addEventListener('beforeunload',e=>{if(activityActive()){e.preventDefault();e.returnValue=''}});

  async function restore(){const raw=sessionStorage.getItem(cfg.sessionStorageKey);if(!raw)return;try{const saved=JSON.parse(raw);if(!saved.attemptId||!saved.token)return clearSaved();state.attemptId=saved.attemptId;state.token=saved.token;const data=await rpc(cfg.rpc.resume,{p_attempt_id:state.attemptId,p_attempt_token:state.token});render(data.snapshot);if(activityActive()&&cfg.requireFullscreen)showFullscreenGate('Team session restored. Return to fullscreen mode to continue.');else hideFullscreenGate()}catch(err){clearSaved();setSetupStatus('The previous session is no longer available. You may register the team again.',true)}}
  restore();
})();
