(()=>{
'use strict';
const cfg=globalThis.IJR_SPECIALIZED_HUB_CONFIG;
const catalog=globalThis.IJR_SPECIALIZED_TRACKS;
const slug=document.body.dataset.track;
const track=catalog?.[slug];
const root=document.getElementById('app');
if(!cfg||!track||!root){document.body.innerHTML='<main style="font-family:sans-serif;padding:40px"><h1>Track unavailable</h1><p>The requested learning hub could not be loaded.</p></main>';return;}
const sb=globalThis.supabase?.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const localKey=cfg.localPrefix+slug;
let state={session:null,questions:[],answers:{},index:0,report:null,busy:false};
const domainNames={foundations:'Fundamentos',applied_reasoning:'Razonamiento aplicado',workflow_tools:'Herramientas + workflow',self_profile:'Autopercepción'};
const levelInfo={
  foundation:{label:'Foundation',copy:'Necesita un puente guiado de fundamentos antes de aumentar la complejidad del proyecto.',next:'Inicia Sprint 1 con apoyo paso a paso y evidencia corta por concepto.'},
  developing:{label:'Developing',copy:'Tiene una base parcial y puede avanzar con andamiaje, ejemplos y checkpoints frecuentes.',next:'Inicia Sprint 1 en la ruta estándar, revisando fundamentos donde el diagnóstico mostró vacíos.'},
  proficient:{label:'Proficient',copy:'Tiene una base funcional para comenzar el proyecto y justificar decisiones técnicas.',next:'Inicia Sprint 1 en la ruta estándar e incorpora retos de transferencia y depuración.'},
  advanced:{label:'Advanced',copy:'Muestra una base sólida para trabajar con mayor autonomía y extensiones de diseño.',next:'Inicia Sprint 1 con extensiones, decisiones de arquitectura y evidencia de mayor profundidad.'}
};
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
function save(){localStorage.setItem(localKey,JSON.stringify({session:state.session,answers:state.answers,index:state.index,report:state.report}));}
function load(){try{return JSON.parse(localStorage.getItem(localKey)||'null')}catch{return null}}
async function rpc(name,args){if(!sb)throw new Error('Supabase client unavailable');const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message||'Backend RPC error');return data;}
function stackHtml(){return track.stack.map(x=>`<span>${esc(x)}</span>`).join('');}
function roadmapHtml(){return track.sprints.map(s=>`<article class="sprint"><div class="sprint-top"><span class="sprint-index">SPRINT ${String(s.n).padStart(2,'0')}</span><span class="tag">Project path</span></div><h3>${esc(s.title)}</h3><p>${esc(s.goal)}</p><div class="deliverable"><strong>Deliverable</strong>${esc(s.deliverable)}</div></article>`).join('');}
function shell(){
  document.title=`Seminar 11 · ${track.title} Learning Hub`;
  root.innerHTML=`<header class="topbar"><a class="brand" href="../"><span class="brand-mark">IJR</span><span><small>Instituto Jorge Robledo · Seminar 11</small><strong>${esc(track.title)} Learning Hub</strong></span></a><div class="top-actions"><a class="button button-light" href="../">All tracks</a><a class="button button-dark" href="../../seminario-oop-uml/">OOP + UML Core</a></div></header>
  <main class="shell"><section class="hero"><div class="hero-copy"><p class="eyebrow">SOFTWARE ENGINEERING STUDIO · SPECIALIZED TRACK</p><h1>${esc(track.title)}</h1><p>Learning Hub dedicado a la ruta especializada. El primer paso es un <strong>diagnóstico individual de entrada</strong> para conocer la base técnica, el razonamiento aplicado y la autopercepción del estudiante antes de comenzar los sprints.</p><div class="stack">${stackHtml()}</div></div><aside class="project-card"><span>PROJECT FRAME</span><strong>${esc(track.project)}</strong><small>Common loop: design → model → implement → test → document → defend.</small></aside></section>
  <section class="section"><div class="section-head"><p class="eyebrow">DIAGNOSTIC 01 · INDIVIDUAL</p><h2>Posicionar antes de enseñar.</h2><p>15 ítems: 12 preguntas objetivas de conocimiento + 3 ítems de autopercepción. La autopercepción <strong>no modifica</strong> el nivel técnico. No es una nota; es una línea base para decidir cuánto andamiaje necesita cada estudiante.</p></div><div id="diagnosticFrame" class="diagnostic-frame" aria-live="polite"></div></section>
  <section class="section"><div class="section-head"><p class="eyebrow">8-SPRINT PROJECT ROADMAP</p><h2>${esc(track.project)}</h2><p>El diagnóstico no bloquea la ruta. Todos pueden avanzar; el nivel determina el tipo de apoyo, profundidad y extensión recomendada.</p></div><div class="roadmap">${roadmapHtml()}</div></section>
  <footer class="footer"><span>Instituto Jorge Robledo · Seminar 11 · Third Period 2026</span><span>${esc(track.title)} · ${esc(track.project)}</span></footer></main>`;
  renderDiagnostic();
}
function introHtml(){return `<div class="diagnostic-intro"><div><p class="eyebrow">ENTRY BASELINE</p><h3>Conocimiento + razonamiento + autopercepción.</h3><p>Responde sin buscar soluciones externas. El objetivo es ubicar tu punto de partida real. Las respuestas correctas se califican en el backend y no se envían al navegador.</p><div class="diagnostic-facts"><div><strong>12</strong><span>Knowledge items</span></div><div><strong>3</strong><span>Self-profile items</span></div><div><strong>4</strong><span>Placement levels</span></div></div></div><form id="startForm" class="registration-box"><p class="eyebrow">INDIVIDUAL REGISTRATION</p><label>Nombre completo<input id="fullName" required minlength="3" maxlength="120" autocomplete="name" placeholder="Nombre y apellidos"></label><label>Grupo<select id="groupCode" required><option value="">Selecciona…</option><option>11-A</option><option>11-B</option><option>11-C</option></select></label><button class="button button-dark" type="submit">Start diagnostic</button><p id="startStatus" class="status" role="status"></p></form></div>`;}
function renderDiagnostic(){const frame=document.getElementById('diagnosticFrame');if(!frame)return;if(state.report){frame.innerHTML=resultHtml(state.report);wireResult();return}if(state.questions.length&&state.session){frame.innerHTML=testHtml();wireTest();return}frame.innerHTML=introHtml();document.getElementById('startForm').addEventListener('submit',startAttempt);}
async function startAttempt(e){e.preventDefault();if(state.busy)return;state.busy=true;const status=document.getElementById('startStatus');status.textContent='Creando intento seguro…';const attemptToken=token();try{const data=await rpc(cfg.rpc.start,{p_track_slug:slug,p_bank_version:cfg.bankVersion,p_full_name:document.getElementById('fullName').value.trim(),p_group_code:document.getElementById('groupCode').value,p_attempt_token:attemptToken,p_user_agent:navigator.userAgent});state.session={attemptId:data.attempt_id,token:attemptToken,fullName:data.full_name,groupCode:data.group_code,startedAt:data.started_at,bankVersion:data.bank_version};state.questions=await rpc(cfg.rpc.questions,{p_track_slug:slug,p_bank_version:cfg.bankVersion});state.answers={};state.index=0;state.report=null;save();renderDiagnostic();}catch(err){status.textContent=`No se pudo iniciar: ${err.message}`;status.className='status error';}finally{state.busy=false;}}
function answeredCount(){return state.questions.reduce((n,q)=>n+(Number.isInteger(state.answers[q.id])?1:0),0)}
function testHtml(){const q=state.questions[state.index];const answered=answeredCount();const pct=Math.round(100*answered/state.questions.length);const nav=state.questions.map((item,i)=>`<button type="button" data-q="${i}" class="${Number.isInteger(state.answers[item.id])?'answered ':''}${i===state.index?'current':''}" aria-label="Pregunta ${i+1}${Number.isInteger(state.answers[item.id])?', respondida':''}">${i+1}</button>`).join('');const options=q.options.map((opt,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${state.answers[q.id]===i?'checked':''}><span class="option-key">${String.fromCharCode(65+i)}</span><span>${esc(opt)}</span></label>`).join('');return `<div class="diagnostic-workspace"><aside class="question-nav"><div class="progress-copy"><strong>${answered}/15 answered</strong><span>${pct}%</span></div><div class="progress-track"><span style="width:${pct}%"></span></div><div class="question-numbers">${nav}</div><div class="legend"><span>● Black = answered</span><span>Outline = current question</span><span>Questions 13–15 are self-profile and are not scored.</span></div></aside><section class="question-stage"><div class="question-meta"><span class="tag">${q.scored?'Knowledge':'Self-profile'}</span><span class="tag">${esc(domainNames[q.domain]||q.domain)}</span><span class="tag">Question ${q.position}/15</span></div><h3>${esc(q.prompt)}</h3><div class="options">${options}</div><div class="question-actions"><button id="prevBtn" class="button button-light" type="button" ${state.index===0?'disabled':''}>← Previous</button><div><button id="nextBtn" class="button button-light" type="button" ${state.index===state.questions.length-1?'disabled':''}>Next →</button><button id="submitBtn" class="button button-dark" type="button" ${answered===15?'':'disabled'}>Submit diagnostic</button></div></div><p id="testStatus" class="status" role="status"></p></section></div>`;}
function wireTest(){document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{state.index=Number(b.dataset.q);save();renderDiagnostic()}));document.querySelectorAll('input[name="answer"]').forEach(r=>r.addEventListener('change',()=>{state.answers[state.questions[state.index].id]=Number(r.value);save();renderDiagnostic()}));document.getElementById('prevBtn')?.addEventListener('click',()=>{state.index=Math.max(0,state.index-1);save();renderDiagnostic()});document.getElementById('nextBtn')?.addEventListener('click',()=>{state.index=Math.min(state.questions.length-1,state.index+1);save();renderDiagnostic()});document.getElementById('submitBtn')?.addEventListener('click',submitAttempt);}
async function submitAttempt(){if(state.busy||answeredCount()!==15)return;state.busy=true;const status=document.getElementById('testStatus');status.textContent='Calificando en el backend…';try{const report=await rpc(cfg.rpc.submit,{p_attempt_id:state.session.attemptId,p_attempt_token:state.session.token,p_answers:state.answers});state.report=report;save();renderDiagnostic();document.getElementById('diagnosticFrame')?.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){status.textContent=`No se pudo enviar: ${err.message}`;status.className='status error';}finally{state.busy=false;}}
function resultHtml(r){const info=levelInfo[r.level]||levelInfo.developing;const domains=['foundations','applied_reasoning','workflow_tools'].map(k=>{const d=r.domain_scores?.[k]||{score:0,max:4,percent:0};return `<article class="domain-card"><strong><span>${esc(domainNames[k])}</span><span>${esc(d.score)}/${esc(d.max)}</span></strong><div class="bar"><span style="width:${Number(d.percent)||0}%"></span></div><small>${esc(d.percent)}%</small></article>`}).join('');return `<div class="result"><div class="result-hero"><div><p class="eyebrow">DIAGNOSTIC REPORT · ${esc(r.group_code||state.session?.groupCode||'')}</p><h3>${esc(info.label)} · ${esc(r.knowledge_percent)}%</h3><p>${esc(info.copy)}</p><p><strong>Next positioning:</strong> ${esc(info.next)}</p></div><div class="result-score"><strong>${esc(r.score)}/${esc(r.max_score)}</strong><span>technical knowledge score</span><div style="margin-top:12px"><strong style="font-size:1.6rem">${esc(r.confidence_percent)}%</strong><span>self-profile index · not graded</span></div></div></div><div class="domain-grid">${domains}</div><div class="result-note"><strong>Interpretación:</strong> este resultado es diagnóstico, no calificación. El nivel técnico usa únicamente las 12 preguntas objetivas. Los 3 ítems de autopercepción se guardan por separado para comparar conocimiento declarado vs desempeño observado.</div><div class="question-actions" style="margin-top:18px"><button id="retakeBtn" class="button button-light" type="button">Start a new attempt</button><a class="button button-dark" href="#roadmapAnchor" onclick="return true">Continue to roadmap</a></div></div>`;}
function wireResult(){document.getElementById('retakeBtn')?.addEventListener('click',()=>{localStorage.removeItem(localKey);state={session:null,questions:[],answers:{},index:0,report:null,busy:false};renderDiagnostic()});const roadmap=document.querySelector('.roadmap');if(roadmap)roadmap.id='roadmapAnchor';}
async function resume(){const local=load();if(!local?.session?.attemptId||!local?.session?.token)return;state.session=local.session;state.answers=local.answers||{};state.index=Math.min(Number(local.index)||0,14);state.report=local.report||null;try{const snap=await rpc(cfg.rpc.snapshot,{p_attempt_id:state.session.attemptId,p_attempt_token:state.session.token});if(snap?.status==='completed'){state.report=snap;save();return}state.questions=await rpc(cfg.rpc.questions,{p_track_slug:slug,p_bank_version:cfg.bankVersion});}catch(err){console.warn('Diagnostic recovery unavailable; starting screen restored.',err);localStorage.removeItem(localKey);state={session:null,questions:[],answers:{},index:0,report:null,busy:false};}}
(async()=>{await resume();shell();})();
})();
