(()=>{
 'use strict';const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),project=Object.hasOwn(window.STUDIO_COURSES,params.get('project'))?params.get('project'):'cyber',course=window.STUDIO_COURSES[project],n=Math.max(1,Math.min(4,Math.trunc(Number(params.get('class'))||1))),lesson=course.classes[n-1],key='ijr-studio-'+project+'-v1';
 let saved;try{saved=JSON.parse(localStorage.getItem(key)||'{}');}catch{saved={};}saved.cells=saved.cells||{};saved.notes=saved.notes||{};
 let active=0,busy=false,worker,request=0,prepared=false,preview,mesh,rotation=0,raf,frameToken,webRequest=0,parts={},dbPromise;const pending=new Map(),executed=new Set(),urls=new Map(),webPending=new Map();
 const cellKey=(c,it)=>c+':'+it.id,item=()=>lesson.cells[active],entry=(c,it)=>saved.cells[cellKey(c,it)]||{},source=(c,it)=>entry(c,it).code??it.code;
 const url=(page,c=n)=>`${page}?project=${project}&class=${c}`;
 function persist(){try{localStorage.setItem(key,JSON.stringify(saved));$('saveStatus').textContent='Borrador y notas guardados en este navegador. Los registros web viven en IndexedDB local.';}catch{$('saveStatus').textContent='Descarga las fuentes: no se pudo conservar el borrador.';}}
 function save(){saved.cells[cellKey(n,item())]={...entry(n,item()),code:$('codeEditor').value};persist();}
 function log(t){$('terminalOutput').textContent+=String(t)+'\n';$('terminalOutput').scrollTop=$('terminalOutput').scrollHeight;}
 function render(){const it=item();$('cellTitle').textContent=$('lessonTitle').textContent=it.title;$('codeInstruction').textContent=$('lessonConcept').textContent=it.purpose;$('codeEditor').value=source(n,it);$('lessonSteps').replaceChildren(...it.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('executionCount').textContent='['+(entry(n,it).runs||' ')+']';$('stepRail').replaceChildren(...lesson.cells.map((s,i)=>{const b=document.createElement('button');b.className='rail-step'+(i===active?' active':'')+(entry(n,s).ok?' done':'');b.textContent=i+1;b.title=s.title;b.disabled=busy;b.onclick=()=>select(i);return b;}));$('progressBar').style.width=lesson.cells.filter(s=>entry(n,s).ok).length/lesson.cells.length*100+'%';$('previousCell').disabled=busy||active===0;$('nextCell').disabled=busy||active===lesson.cells.length-1;}
 function select(i){if(busy)return;save();active=i;render();}
 function lock(v){busy=v;for(const id of ['runCodeButton','runCellButton','resetCodeButton','restartRuntime','downloadNotebook','downloadPython'])$(id).disabled=v;$('codeEditor').readOnly=v;$('terminalCommand').disabled=v;$('terminalForm').querySelector('button').disabled=v;$('classNav').style.pointerEvents=v?'none':'';renderRailLock();}
 function renderRailLock(){for(const b of $('stepRail').children)b.disabled=busy;$('previousCell').disabled=busy||active===0;$('nextCell').disabled=busy||active===lesson.cells.length-1;}
 function download(name,text,type='text/plain'){const prior=urls.get(name);if(prior){URL.revokeObjectURL(prior.url);prior.a.remove();}const blob=new Blob([text],{type}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.textContent='Guardar '+name;$('artifactButtons').appendChild(a);a.className='ghost-button';urls.set(name,{url:u,a});a.click();}
 function python(code){
  if(!worker){worker=new Worker('worker.js?v=1');worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;if(data.status==='loading'){$('runtimeBadge').textContent='Cargando Python…';return;}clearTimeout(p.timer);pending.delete(data.id);$('runtimeBadge').textContent='Python listo';p.resolve(data);};worker.onerror=()=>reset('Error al cargar Python. Revisa la conexión.');}
  const all=course.classes.flatMap((cl,c)=>cl.cells.filter(it=>it.language==='python'&&!['test','modify','qa','regression','measure'].includes(it.id)).map(it=>source(c+1,it))).join('\n');
  const id=++request;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reset('Tiempo agotado. Revisa el código y ejecuta de nuevo.'),60000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,code,support:window.STUDIO_SUPPORT,source:all});});
 }
 function reset(reason='Runtime reiniciado. Borradores conservados.') {worker?.terminate();worker=null;prepared=false;executed.clear();for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error(reason));}pending.clear();log(reason);}
 function meshDraw(){
  if(!mesh)return;const canvas=$('animationCanvas'),ctx=canvas.getContext('2d'),v=mesh.vertices,scale=2.7,angle=rotation;
  const points=v.map(([x,y,z])=>{const a=x*Math.cos(angle)-y*Math.sin(angle),b=x*Math.sin(angle)+y*Math.cos(angle);return [360+(a-b)*scale*.7,300+(a+b)*scale*.32-z*scale];});ctx.fillStyle='#eef2f8';ctx.fillRect(0,0,720,480);
  const triangles=mesh.triangles.map(t=>({t,depth:t.reduce((s,i)=>s+v[i][1]+v[i][0],0)})).sort((a,b)=>a.depth-b.depth);
  triangles.forEach(({t},i)=>{ctx.beginPath();t.forEach((j,k)=>k?ctx.lineTo(...points[j]):ctx.moveTo(...points[j]));ctx.closePath();ctx.fillStyle=['#8ab4f8','#aecbfa','#669df6'][i%3];ctx.fill();ctx.strokeStyle='#174ea6';ctx.stroke();});ctx.fillStyle='#174ea6';ctx.font='18px Arial';ctx.fillText('Modelo calculado en Python · medidas en mm',20,35);
 }
 function updateOutput(raw){if(!raw)return;preview=JSON.parse(raw);$('outputNote').textContent=preview.note||course.note;$('frameInfo').textContent=preview.kind==='mesh'?`${preview.vertices.length} vértices · ${preview.triangles.length} triángulos`:'Resultado del código';
  if(preview.kind==='mesh'){mesh=preview;$('animationCanvas').classList.remove('hidden');$('previewTable').replaceChildren();meshDraw();$('playPreview').disabled=$('pausePreview').disabled=false;}
  if(preview.kind==='table'){$('previewTable').replaceChildren();const table=document.createElement('table');for(const [i,row] of [preview.headers,...preview.rows].entries()){const tr=document.createElement('tr');for(const value of row){const td=document.createElement(i?'td':'th');td.textContent=value;tr.appendChild(td);}table.appendChild(tr);}$('previewTable').appendChild(table);}
  if(preview.artifacts){for(const [name,text] of preview.artifacts.map(a=>[a.name,a.text])){let b=$('artifactButtons').querySelector(`[data-artifact="${name}"]`);if(!b){b=document.createElement('button');b.className='run-button';b.dataset.artifact=name;$('artifactButtons').appendChild(b);}b.textContent='Descargar '+name;b.onclick=()=>download(name,text);}$('downloadAnimation').disabled=false;}
 }
 const escapeScript=s=>String(s).replace(/<\/script/gi,'<\\/script');
 function standalone(){return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${course.title}</title><style>${parts.css||''}</style><body>${parts.html||''}<script>(async()=>{const db=await (${window.STUDIO_DB.standaloneSource()})(${JSON.stringify(project)});${escapeScript(parts.js||'')}\n})().catch(e=>{console.error(e);const el=document.getElementById('status');if(el)el.textContent=e.message;});<\/script></body></html>`;}
 function web(code,part){
  if(part)parts[part]=code;
  const token=crypto.randomUUID();frameToken=token;const id=++webRequest;
  const bridge=`const token=${JSON.stringify(token)};let seq=0;const waiting=new Map();const send=o=>parent.postMessage({...o,token},'*');const db=(op,row)=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});send({kind:'db',id,op,row});setTimeout(()=>{if(waiting.has(id)){waiting.delete(id);reject(new Error('Tiempo agotado en la base local'));}},10000);});addEventListener('message',e=>{if(e.source!==parent||e.data.token!==token)return;const p=waiting.get(e.data.id);if(!p)return;waiting.delete(e.data.id);e.data.error?p.reject(new Error(e.data.error)):p.resolve(e.data.value);});const assert=(ok,msg='Prueba fallida')=>{if(!ok)throw new Error(msg);};console.log=(...args)=>send({kind:'log',text:args.map(String).join(' ')});addEventListener('error',e=>send({kind:'log',text:e.message}));`;
  const html=`<!doctype html><html lang="es"><meta charset="utf-8"><style>${parts.css||''}</style><body>${parts.html||''}<script>${bridge}\n(async()=>{try{${escapeScript(parts.js||'')}\n${part?'':escapeScript(code)}\nsend({kind:'result',id:${id},ok:true});}catch(e){send({kind:'result',id:${id},ok:false,error:e.message});}})();<\/script></body></html>`;
  $('webPreview').classList.remove('hidden');$('frameInfo').textContent='HTML/CSS/JavaScript ejecutados';$('outputNote').textContent='Base de datos IndexedDB real, local a este navegador. No se envían datos al servidor ni a GTA V.';$('downloadAnimation').disabled=false;
  return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{webPending.delete(id);reject(new Error('Tiempo agotado. Revisa bucles o errores JavaScript.'));},20000);webPending.set(id,{resolve,reject,timer,token});$('webPreview').srcdoc=html;});
 }
 window.addEventListener('message',async e=>{const d=e.data;if(e.source!==$('webPreview').contentWindow||!d||d.token!==frameToken)return;
  if(d.kind==='log'){log(d.text);return;}if(d.kind==='result'){const p=webPending.get(d.id);if(!p||p.token!==d.token)return;clearTimeout(p.timer);webPending.delete(d.id);p.resolve({ok:d.ok,output:'',error:d.error});return;}
  if(d.kind==='db'){try{dbPromise??=window.STUDIO_DB.openDatabase(project);const db=await dbPromise;const value=await db(d.op,d.row);if(e.source===$('webPreview').contentWindow&&d.token===frameToken)e.source.postMessage({token:d.token,id:d.id,value},'*');}catch(error){e.source.postMessage({token:d.token,id:d.id,error:error.message},'*');}}
 });
 async function perform(c,it,code=source(c,it)){log(`>>> C${c}: ${it.title}`);const result=course.mode==='python'?await python(code):await web(code,it.part);log(result.output);if(!result.ok){log(result.error);throw new Error(result.error);}if(result.preview)updateOutput(result.preview);executed.add(cellKey(c,it));return result;}
 async function prepare(){if(prepared)return;for(let c=1;c<n;c++)for(const it of course.classes[c-1].cells){if(['test','qa','regression','measure','measurement'].includes(it.id)||(it.id==='modify'&&!entry(c,it).ok))continue;if(course.mode==='web'&&!it.part)continue;await perform(c,it);}prepared=true;}
 async function execute(code,terminal=false){if(busy)return;save();lock(true);$('activityStatus').textContent='Ejecutando…';try{await prepare();if(!terminal)for(let i=0;i<active;i++){const it=lesson.cells[i];if(!executed.has(cellKey(n,it)))await perform(n,it);}const it=terminal?{id:'terminal',title:'Terminal',language:course.mode==='python'?'python':'javascript',part:null}:item();await perform(n,it,code);if(!terminal){saved.cells[cellKey(n,it)]={...entry(n,it),code,ok:true,runs:(entry(n,it).runs||0)+1};persist();}$('activityStatus').textContent='Código ejecutado · comprueba el resultado y las pruebas';$('activityStatus').className='validation-status ok';}catch(e){log(e.message);if(!terminal){saved.cells[cellKey(n,item())]={...entry(n,item()),ok:false};persist();}$('activityStatus').textContent='Error real · corrige y vuelve a ejecutar';$('activityStatus').className='validation-status bad';}finally{lock(false);render();}}
 $('projectTitle').textContent=course.title;$('projectBadge').textContent=project.toUpperCase();$('classLabel').textContent=`Clase ${n}/4 · ${lesson.title}`;$('lessonTag').textContent=`C${n} · WORKSHOP`;$('classGate').textContent=lesson.gate;$('uml').textContent=lesson.uml.join(' → ');$('kernelLabel').textContent=course.mode==='python'?'Python 3 · runtime real':'HTML · CSS · JavaScript · IndexedDB';$('runtimeBadge').textContent=course.mode==='python'?'Python por iniciar':'Web runtime listo';$('terminalCommand').placeholder=course.mode==='python'?'print("hola")':'console.log(await db("list"))';$('codeEditor').setAttribute('aria-label',course.mode==='python'?'Python code editor':'Web code editor');
 for(const id of ['theoryLink','theorySide'])$(id).href=url('theory.html');for(const a of document.querySelectorAll('a[href="index.html"]'))a.href='index.html?project='+project;
 course.classes.forEach((c,i)=>{const a=document.createElement('a');a.href=url('workshop.html',i+1);a.className='class-link'+(i+1===n?' active':'');a.textContent='Clase '+(i+1);$('classNav').appendChild(a);});
 $('runCodeButton').onclick=$('runCellButton').onclick=()=>execute($('codeEditor').value);$('codeEditor').oninput=()=>{save();for(let i=active;i<lesson.cells.length;i++)executed.delete(cellKey(n,lesson.cells[i]));};$('codeEditor').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();execute($('codeEditor').value);}};
 $('previousCell').onclick=()=>select(active-1);$('nextCell').onclick=()=>select(active+1);$('resetCodeButton').onclick=()=>{$('codeEditor').value=item().code;save();executed.delete(cellKey(n,item()));};$('clearTerminalButton').onclick=()=>{$('terminalOutput').textContent='';};$('terminalForm').onsubmit=e=>{e.preventDefault();execute($('terminalCommand').value,true);};
 $('playPreview').onclick=()=>{cancelAnimationFrame(raf);const tick=()=>{rotation+=.01;meshDraw();raf=requestAnimationFrame(tick);};tick();};$('pausePreview').onclick=()=>{cancelAnimationFrame(raf);rotation=0;meshDraw();};
 $('downloadAnimation').onclick=()=>{if(course.mode==='web')download(project+'-app.html',standalone(),'text/html');else for(const [name,text] of (preview?.artifacts||[]).map(a=>[a.name,a.text]))download(name,text);};
 $('downloadNotebook').onclick=()=>{save();if(course.mode==='python'){const allSource=course.classes.flatMap((c,i)=>c.cells.map(it=>source(i+1,it))).join('\n');const bootstrap='SERVER_TAIL = '+JSON.stringify(window.STUDIO_SUPPORT.serverTail)+'\nPROBE_SOURCE = '+JSON.stringify(window.STUDIO_SUPPORT.probe)+'\nLAB_SOURCE = '+JSON.stringify(allSource)+'\n';const cells=[{cell_type:'code',metadata:{},execution_count:null,outputs:[],source:[bootstrap]},...course.classes.flatMap((c,i)=>[{cell_type:'markdown',metadata:{},source:['# '+c.title]},...c.cells.map(it=>({cell_type:'code',metadata:{},execution_count:null,outputs:[],source:[source(i+1,it)]}))])];download(project+'.ipynb',JSON.stringify({nbformat:4,nbformat_minor:5,metadata:{kernelspec:{display_name:'Python 3',language:'python',name:'python3'}},cells},null,2),'application/json');}else download(project+'-fuentes.json',JSON.stringify({project,parts,classes:course.classes.map((c,i)=>({...c,cells:c.cells.map(it=>({...it,code:source(i+1,it)}))}))},null,2),'application/json');};
 $('downloadPython').onclick=async()=>{try{if(course.mode==='web'){dbPromise??=window.STUDIO_DB.openDatabase(project);download(project+'-datos.json',JSON.stringify(await(await dbPromise)('list'),null,2),'application/json');}else download(project+'-resultado.json',JSON.stringify(preview,null,2),'application/json');}catch(e){log(e.message);}};
 $('downloadEvidence').onclick=()=>download(project+'-evidencia.json',JSON.stringify({project,cells:saved.cells,notes:saved.notes,exportedAt:new Date().toISOString(),review:'Pendiente de revisión docente'},null,2),'application/json');$('evidenceNotes').value=saved.notes[n]||'';$('evidenceNotes').oninput=()=>{saved.notes[n]=$('evidenceNotes').value;persist();};$('restartRuntime').onclick=()=>{reset();cancelAnimationFrame(raf);};render();
})();
