(()=>{
 'use strict';
 const params=new URLSearchParams(location.search),project=window.RICO_COURSE?'rico':Object.hasOwn(window.STUDIO_COURSES||{},params.get('project'))?params.get('project'):'cyber',classNo=Math.max(1,Math.min(4,Math.trunc(Number(params.get('class'))||1))),course=window.RICO_COURSE||window.STUDIO_COURSES[project].classes,lesson=course[classNo-1],key='ijr-seminar-shared-team-v1:'+project;
 const $=id=>document.getElementById(id),normalize=v=>String(v||'').trim().toLowerCase(),valid=v=>v.length<=254&&/^[^\s@]+@ijr\.edu\.co$/.test(v),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let session,queue=[],syncing=false,resolveReady,completed=new Set();try{const prev=JSON.parse(sessionStorage.getItem(key)||'null');if(prev?.team_token){session=prev;queue=prev.pending||[];}}catch{}
 // Retain evidence from expired sessions without replaying it into a new team.
 if(session?.expires_at&&Date.parse(session.expires_at)<=Date.now()){
  if(queue.length)try{localStorage.setItem('ijr-seminar-expired-team-evidence:'+session.team_id,JSON.stringify({team_id:session.team_id,member_emails:session.member_emails,project_key:project,pending:queue,approval:'Sin sincronizar; vuelve a ejecutar con una sesión activa.'}));}catch{}
  session=undefined;queue=[];sessionStorage.removeItem(key);
 }
 const ready=new Promise(resolve=>resolveReady=resolve);
 const panel=document.createElement('section');panel.className='seminar-shared-progress';panel.id='sharedTeamProgress';panel.innerHTML='<strong id="sharedTeamLabel">Registra los integrantes para compartir el progreso.</strong><p id="sharedTeamStatus" aria-live="polite"></p><button id="retryTeamSync" class="ghost-button" hidden>Reintentar sincronización</button>';
 document.querySelector('.workspace-topline').after(panel);
 function keep(){try{sessionStorage.setItem(key,JSON.stringify({...session,pending:queue}));}catch{$('sharedTeamStatus').textContent='No se pudo guardar la cola local. Mantén la pestaña abierta y reintenta la sincronización.';}}
 function snapshot(){return session?{team_id:session.team_id,project_key:project,class_no:classNo,team_size:session.team_size,member_emails:session.member_emails,cells:session.cells||[],pending:queue.length,approval:'Progreso de práctica; aprobación docente aparte'}:null;}
 function status(){if(!session)return;const count=lesson.cells.filter(it=>completed.has(classNo+':'+it.id)).length;$('sharedTeamLabel').textContent=`${session.team_size} integrante${session.team_size===1?'':'s'} · ${session.member_emails.join(' · ')}`;$('sharedTeamStatus').textContent=queue.length?`${queue.length} ejecución(es) pendientes de sincronizar. El progreso de los compañeros se actualizará al recuperar la conexión.`:`Supabase · Clase ${classNo}: ${count}/${lesson.cells.length} celdas en común. Cada nueva ejecución correcta se registra para todos los integrantes.`;$('retryTeamSync').hidden=false;$('retryTeamSync').textContent=queue.length?'Reintentar sincronización':'Actualizar progreso';}
 function apply(data){session={...session,...data};completed=new Set((data.cells||[]).map(it=>it.class_no+':'+it.cell_id));keep();status();window.dispatchEvent(new CustomEvent('ijr:seminar-team-progress',{detail:snapshot()}));}
 async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('https://rlfxnjbqxbozjdzkbwlz.supabase.co/functions/v1/seminar-workshop-team',{method:'POST',headers:{'Content-Type':'application/json',apikey:'sb_publishable_rmVOQ3Orx49KpW_4uMqYew_c2HpcA87'},body:JSON.stringify(body),signal:controller.signal});const data=await r.json();if(!r.ok)throw new Error(data.error==='team_session_expired'?'La sesión del equipo venció. Descarga tu evidencia y vuelve a registrar el equipo.':data.error||'No se pudo sincronizar el equipo.');return data;}finally{clearTimeout(timer);}}
 async function flush(){if(syncing||!session)return;syncing=true;try{while(queue.length){const data=await api({action:'record',team_token:session.team_token,...queue[0]});queue.shift();apply(data);}}catch(e){status();$('sharedTeamStatus').textContent+=' '+(e.name==='AbortError'?'Tiempo de espera agotado.':e.message);$('retryTeamSync').hidden=false;}finally{syncing=false;keep();}}
 async function record(cellId,code,output){await ready;const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code)),codeHash=Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');queue.push({class_no:classNo,cell_id:cellId,code_hash:codeHash,output:String(output||'').slice(0,4000),request_id:crypto.randomUUID(),success:true});keep();status();await flush();return queue.length===0;}
 window.IJR_SEMINAR_TEAM={ready,record,snapshot,isComplete:(c,id)=>completed.has(c+':'+id)};
 async function refresh(){if(!session||syncing)return;try{if(queue.length)await flush();else apply(await api({action:'progress',team_token:session.team_token,class_no:classNo}));}catch(e){$('sharedTeamStatus').textContent='No se pudo actualizar el progreso. Reintenta cuando tengas conexión.';}}
 $('retryTeamSync').onclick=refresh;window.addEventListener('online',refresh);window.addEventListener('focus',()=>{if(!document.getElementById('stat11TeamGate'))refresh();});
 let owner='';try{owner=normalize(JSON.parse(localStorage.getItem('ijr-seminar-main-registration-v2')||'null')?.institutionalEmail);}catch{}
 const gate=document.createElement('div');gate.id='stat11TeamGate';gate.className='stat11-team-gate';gate.setAttribute('role','dialog');gate.setAttribute('aria-modal','true');gate.setAttribute('aria-labelledby','stat11TeamTitle');
 gate.innerHTML=`<div class="stat11-team-card"><div class="stat11-team-kicker">Seminario 11 · Workshop start</div><h1 id="stat11TeamTitle">Who is working at this computer?</h1><p class="stat11-team-lead"><strong>${esc(lesson.title)}</strong><br>Registra cada integrante con su correo institucional para compartir el progreso de este Workshop.</p><div class="stat11-team-lab-note"><div>🖥️</div><div><strong>9-computer laboratory</strong>Each workstation can be used by 1, 2 or 3 students. Las nuevas ejecuciones correctas se guardan en Supabase para todos los integrantes.</div></div><form id="stat11TeamForm" novalidate><span class="stat11-team-size-label">How many students are participating?</span><div class="stat11-team-size-options" role="radiogroup" aria-label="Number of participating students">${[1,2,3].map(n=>`<label class="stat11-team-size-option"><input type="radio" name="stat11TeamSize" value="${n}"><span>${n} student${n===1?'':'s'}</span></label>`).join('')}</div><div class="stat11-team-members">${[1,2,3].map(n=>`<div class="stat11-team-member${n>1?' hidden':''}" id="stat11TeamMember${n}"><label for="stat11TeamEmail${n}">Student ${n} · institutional email</label><input id="stat11TeamEmail${n}" type="email" maxlength="254" autocomplete="${n===1?'email':'off'}" placeholder="student@ijr.edu.co" ${n===1&&valid(owner)?`readonly value="${esc(owner)}"`:''}>${n===1?'<small>Cuenta institucional que utiliza este computador.</small>':''}</div>`).join('')}</div><div class="stat11-team-foot"><div id="stat11TeamStatus" class="stat11-team-status">Choose 1, 2 or 3 students, then use only @ijr.edu.co institutional emails.</div><button id="stat11TeamStart" class="stat11-team-start" type="submit">Start workshop</button></div></form></div>`;
 document.body.appendChild(gate);document.documentElement.classList.add('stat11-team-gate-open');
 let size=0;
 for(const input of gate.querySelectorAll('input[name="stat11TeamSize"]'))input.onchange=()=>{size=Number(input.value);for(let n=1;n<=3;n++){$('stat11TeamMember'+n).classList.toggle('hidden',n>size);$('stat11TeamEmail'+n).required=n<=size;}if(size>=2)$('stat11TeamEmail2').focus();};
 $('stat11TeamForm').onsubmit=async e=>{e.preventDefault();const emails=Array.from({length:size},(_,i)=>normalize($('stat11TeamEmail'+(i+1)).value)),notice=$('stat11TeamStatus');if(!size||emails.some(v=>!valid(v))||new Set(emails).size!==size){notice.textContent='Selecciona 1, 2 o 3 integrantes y escribe correos @ijr.edu.co diferentes.';notice.className='stat11-team-status error';return;}
  $('stat11TeamStart').disabled=true;notice.textContent='Registrando el equipo y recuperando su progreso…';
  try{if(queue.length){await flush();if(queue.length)throw new Error('Sincroniza primero las ejecuciones pendientes del equipo anterior.');}const data=await api({action:'start',project_key:project,class_no:classNo,emails});queue=[];session=data;apply(data);document.documentElement.classList.remove('stat11-team-gate-open');gate.remove();resolveReady(snapshot());window.dispatchEvent(new CustomEvent('ijr:seminar-team-started',{detail:snapshot()}));}catch(error){notice.textContent=error.name==='AbortError'?'No se pudo conectar con Supabase. Reintenta.':error.message;notice.className='stat11-team-status error';$('stat11TeamStart').disabled=false;}
 };
})();
