#!/usr/bin/env node
'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260827163500_python_hub_roster_sync_2026_08_27_v31.sql'),'utf8');

for(const token of [
  "'2026-08-27'",
  "'teacher_provided'",
  "(15,'RODRIGUEZ PEÑA JERONIMO')",
  "(6,'CARDONA VILLEGAS ANTONIA')",
  "group_code='11A')<>17",
  "group_code='11B')<>21",
  "group_code='11C')<>23",
  'normalized_name=public.normalize_student_name(r.name)',
  "id='91693734-901e-4a54-b1c4-c0480da2b151'::uuid"
]){
  if(!sql.includes(token)) throw new Error(`V31 roster sync missing: ${token}`);
}

const groups={
  '11A':['ARANGO GIRALDO JUAN PABLO','ARISTIZABAL CORREA MATIAS','AVILA GIRALDO ALEJANDRO','BOTERO VALENCIA JOSE MATIAS','CUBIDES DASUKY DANIEL','DIAZ AGUDELO SIMON','ESCOBAR DOMINGUEZ SUSANA','GOMEZ CANO SAMUEL','GOMEZ CASTRILLON ANTONIA','LONDOÑO PALACIO MIGUEL ANGEL','MAZO LOPEZ JERONIMO','MORENO CARDEÑO JUAN ANDRES','ORTIZ MORALES SUSANA','OSORIO CAMPILLO MIGUEL ANGEL','RODRIGUEZ PEÑA JERONIMO','SORZA OSPINA LUCIANA','TORO AVILA JUAN JOSE'],
  '11B':['ARBELAEZ ESCOBAR PEDRO PABLO','AUBAD ACEBEDO EMMA','BAUTISTA GIRALDO JERONIMO','BETANCUR OSSA MARIA CAMILA','CARDONA GONZALEZ DAREN','CARDONA VILLEGAS ANTONIA','CHAVARRIAGA AVENDAÑO SAMUEL','GALLEGO ORTEGA MARIA DEL MAR','GIRALDO HINESTROZA MARIAJOSE','GOMEZ TAMAYO MARIA ANTONIA','GUZMAN GOMEZ JACOBO','JARAMILLO ALVAREZ PABLO','JARAMILLO PALACIO PABLO','LOPEZ VINASCO SOFIA','LOTERO MUÑOZ SARA','PALACIO ORREGO ISABELLA','POSADA GONZALEZ MARIA DEL MAR','POSADA HIGUITA SOFIA','REMACHE LOPEZ EMMANUEL','RESTREPO OSPINA ISABEL','RICO PARAMO ALEJANDRO'],
  '11C':['ARANGO SIERRA JUANA INES','BOLIVAR JARAMILLO ISABEL','BUITRAGO VALENCIA MARIANA','CORTES PAJON SAMUEL','DASUKY RIVERA KEMEL','ECHAVARRIA GUTIERREZ MARIANA','GONZALEZ GIRALDO TOMAS','GUISAO ECHAVARRIA ISABEL','GUZMAN GOMEZ MATIAS','HOYOS RESTREPO JERONIMO','LATORRE AREIZA JUAN ANDRES','MOLINA CASTRO ARIANA','MOYA GOMEZ VIOLETA','OTERO ARANGO LUCIANA MARIA','PALACIO MEJIA ANA SOFIA','PALACIO ORREGO MARIA PAULINA','PENAGOS VON WERDER VALENTINA YAZMIN','POVEDA ARTUNDUAGA MANUELA','RINCON TORRES ALEJANDRO','RODRIGUEZ BASTIDAS NICOLAS','VALENCIA VASQUEZ JERONIMO','VARGAS SUAREZ SIMON','VELASQUEZ BELTRAN SAMUEL']
};
for(const [group,names] of Object.entries(groups)){
  for(const name of names){if(!sql.includes(`'${name}'`)) throw new Error(`${group} roster name missing: ${name}`);}
}
if(groups['11A'].includes('CARDONA VILLEGAS ANTONIA')) throw new Error('Cardona Villegas must not remain in 11A.');
if(!groups['11B'].includes('CARDONA VILLEGAS ANTONIA')) throw new Error('Cardona Villegas must be in 11B.');
console.log('PYTHON HUB ROSTER SYNC V31 QA PASS');
console.log('11A=17 11B=21 11C=23 total=61 full_names=PASS roster_date=2026-08-27');
