const {installTeamFixture}=require('./seminar-team-fixture.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{fs.mkdirSync('work',{recursive:true});const browser=await chromium.launch({...(process.env.TEAM_TEST_BROWSER?{executablePath:process.env.TEAM_TEST_BROWSER}:{}),headless:true}),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));if(!process.env.SEMINAR_TEAM_REAL_API)await installTeamFixture(page);const base=process.env.TEAM_TEST_BASE||'http://127.0.0.1:4173/seminario-projects/',prefix='qa.browser.'+Date.now(),emails=[1,2,3].map(i=>`${prefix}.${i}@ijr.edu.co`),teams=[];
async function start(count,members){await page.getByText(count+' student'+(count===1?'':'s'),{exact:true}).click();for(let i=0;i<count;i++)await page.locator('#stat11TeamEmail'+(i+1)).fill(members[i]);await page.locator('#stat11TeamStart').click();await page.locator('#stat11TeamGate').waitFor({state:'detached',timeout:30000});teams.push(await page.evaluate(()=>window.IJR_SEMINAR_TEAM.snapshot().team_id));}
async function run(){await page.locator('#runCodeButton').click();await page.waitForFunction(()=>!document.querySelector('#runCodeButton').disabled,{},{timeout:90000});}
await page.goto(base+'rico/workshop.html?class=1');await page.getByText('2 students',{exact:true}).click();await page.locator('#stat11TeamEmail1').fill(emails[0]);await page.locator('#stat11TeamEmail2').fill(emails[0]);await page.locator('#stat11TeamStart').click();assert.equal(await page.locator('#stat11TeamGate').count(),1);await page.locator('#stat11TeamEmail2').fill(emails[1]);await page.locator('#stat11TeamStart').click();await page.locator('#stat11TeamGate').waitFor({state:'detached',timeout:30000});teams.push(await page.evaluate(()=>window.IJR_SEMINAR_TEAM.snapshot().team_id));await run();assert.match(await page.locator('#sharedTeamStatus').innerText(),/1\/4 celdas/);
await page.locator('#stepRail button').nth(1).click();await page.locator('#codeEditor').fill('raise ValueError("QA deliberate failure")');await run();assert.match(await page.locator('#activityStatus').innerText(),/Error Python real/);assert.match(await page.locator('#sharedTeamStatus').innerText(),/1\/4 celdas/);
await page.locator('#resetCodeButton').click();await run();assert.match(await page.locator('#sharedTeamStatus').innerText(),/2\/4 celdas/);
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'work/seminar-team-shared.png',fullPage:true});
await page.goto(base+'rico/workshop.html?class=1');await start(1,[emails[1]]);assert.match(await page.locator('#sharedTeamStatus').innerText(),/2\/4 celdas/);assert.equal(await page.locator('#stepRail .done').count(),2);
await page.goto(base+'studio/workshop.html?project=clients&class=1');await start(3,emails);await run();assert.match(await page.locator('#sharedTeamStatus').innerText(),/1\/3 celdas/);assert.equal(await page.locator('#stepRail .done').count(),1);
await page.goto(base+'studio/workshop.html?project=clients&class=1');await start(1,[emails[2]]);assert.match(await page.locator('#sharedTeamStatus').innerText(),/1\/3 celdas/);assert.equal(await page.locator('#stepRail .done').count(),1);
await page.goto(base+'rico/workshop.html?class=2');await start(1,[emails[0]]);const started=await page.evaluate(()=>window.IJR_SEMINAR_TEAM.snapshot());
// Force only the sync transport offline; Python stays real and reaches a completed run.
const failSync=r=>r.abort();await page.route('**/seminar-workshop-team',failSync);await run();assert.match(await page.locator('#sharedTeamStatus').innerText(),/pendientes/);assert.equal(await page.locator('#stepRail .done').count(),0);await page.unroute('**/seminar-workshop-team',failSync);await page.locator('#retryTeamSync').click();await page.waitForFunction(()=>document.querySelector('#sharedTeamStatus').textContent.includes('1/3 celdas'));assert.equal(await page.locator('#stepRail .done').count(),1);
fs.writeFileSync('work/team-browser-test.json',JSON.stringify({prefix,emails,teams},null,2));assert.deepEqual(errors,[]);console.log('PASS team modal 1/2/3, duplicates rejected, two-person Python progress, failed cell no credit, independent resume, three-person HTML progress, offline queue and retry');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
